// src/lib/db/marts.ts — the Phase-2 analytics mart layer.
//
// TWO responsibilities, kept side by side so the math is provable DB-free:
//
//  1. PURE FORMULA MIRROR (the part `test/marts.test.ts` asserts). These tiny exported
//     helpers replicate — exactly — the arithmetic the SQL views in `drizzle/0007_marts.sql`
//     perform in Postgres. Because the SQL and the TS share one definition of "result",
//     "margin", "sumCosts", "subletNet", … we can unit-test the locked formula without a
//     database (the pure-TS-mirror harness chosen in Plan 01; no pg-mem dependency — T-02-SC).
//     If the SQL and these helpers ever drift, that is a bug — they are the same contract.
//
//  2. TYPED `pgView(...).existing()` HANDLES (the part the RSC dashboard pages read). The
//     view DDL is hand-written in `drizzle/0007_marts.sql` (the FILTER-heavy SQL is clearer
//     hand-written, matching the 0001/0002 convention); Drizzle references those existing
//     views with `.existing()` so Server Components get typed `.select()` access under the
//     caller's JWT + RLS. No view DDL is generated by Drizzle here — `.existing()` only
//     describes the column shape so reads are typed.
//
// THE LOCKED HOUSEHOLD FORMULA (BI-01, D2-11):
//     result = revenue − investimento − costs + sublet_net
//     margin = result / revenue        (null when revenue = 0 — never divide by zero)
// where the household revenue/costs SUMs EXCLUDE the sublocacao gross legs (and never
// include investimento or transferencia — CAT-06), and `sublet_net` is the Sublocação
// profit-center's signed net, counted EXACTLY ONCE (D2-06/07/08).
//
// No € amounts, no PII, no real merchant/tenant names live in this file — only formulas.

import { pgView, type AnyPgColumn } from "drizzle-orm/pg-core";
import { integer, numeric, text } from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Shared row shape the pure mart formulas consume.
// ---------------------------------------------------------------------------

/** The engine's possible `flow_type` outputs (mirrors the `flow_type` pg enum). */
export type MartFlowType = "revenue" | "cost" | "investimento" | "transferencia";

/**
 * A minimal classified-transaction row the pure mart formulas read. `flowType` and
 * `costCenter` are the rules engine's outputs (the `rules.test.ts` contract); the marts
 * only read them — they never re-classify. `amount` is the POSITIVE magnitude of the
 * relevant leg (the SQL views handle sign via `amount_eur` / `-amount_eur` FILTERs; the
 * pure mirror takes positive magnitudes so the test fixtures read naturally).
 */
export interface MartTx {
  flowType: MartFlowType;
  amount: number;
  costCenter: string;
  categoryId: string | null;
}

/** The four buckets the locked P&L formula consumes. */
export interface PnlBuckets {
  revenue: number;
  investimento: number;
  costs: number;
  subletNet: number;
}

// ---------------------------------------------------------------------------
// Pure formula mirror — the SQL views in 0007_marts.sql replicate this EXACTLY.
// ---------------------------------------------------------------------------

/**
 * Household revenue SUM (CAT-06 + D2-07): only `flow_type='revenue'` rows count, and the
 * `sublocacao` gross legs are EXCLUDED (they belong to the sublet profit-center, not the
 * household). investimento and transferencia never count — they are not `revenue`.
 *
 * SQL mirror (0007 v_pnl_monthly):
 *   sum(amount_eur) filter (where flow_type='revenue' and cost_center <> 'sublocacao')
 */
export function sumRevenue(rows: MartTx[]): number {
  return rows
    .filter((r) => r.flowType === "revenue" && r.costCenter !== "sublocacao")
    .reduce((acc, r) => acc + r.amount, 0);
}

/**
 * Household costs SUM (CAT-06 + D2-07): only `flow_type='cost'` rows count, and the
 * `sublocacao` gross legs are EXCLUDED. investimento and transferencia never count.
 *
 * SQL mirror (0007 v_pnl_monthly):
 *   sum(-amount_eur) filter (where flow_type='cost' and cost_center <> 'sublocacao')
 */
export function sumCosts(rows: MartTx[]): number {
  return rows
    .filter((r) => r.flowType === "cost" && r.costCenter !== "sublocacao")
    .reduce((acc, r) => acc + r.amount, 0);
}

/**
 * investimento SUM — its OWN line in the P&L (subtracted in `result`, but explicitly NOT a
 * "cost"). The €4k legs feed the €100k goal; they are excluded from both revenue and costs.
 *
 * SQL mirror (0007 v_pnl_monthly):
 *   sum(-amount_eur) filter (where flow_type='investimento')
 */
export function sumInvestimento(rows: MartTx[]): number {
  return rows
    .filter((r) => r.flowType === "investimento")
    .reduce((acc, r) => acc + r.amount, 0);
}

/**
 * The Sublocação profit-center net (D2-06/07/08) — the signed net of the sublet's gross
 * legs (rent received − costs paid), counted EXACTLY ONCE. This is the ONLY place the
 * sublet gross legs are read; the household SUMs exclude them (cost_center <> 'sublocacao').
 *
 * SQL mirror (0007 v_sublet_pnl.sublet_net), where only `cost_center='sublocacao'` rows
 * are scanned:
 *   sum(amount_eur) filter (where flow_type='revenue')        -- received
 *     − sum(amount_eur) filter (where flow_type='cost')       -- paid
 * (the pure mirror takes positive magnitudes, so net = received − paid).
 */
export function subletNet(rows: MartTx[]): number {
  const sublet = rows.filter((r) => r.costCenter === "sublocacao");
  const received = sublet
    .filter((r) => r.flowType === "revenue")
    .reduce((acc, r) => acc + r.amount, 0);
  const paid = sublet
    .filter((r) => r.flowType === "cost")
    .reduce((acc, r) => acc + r.amount, 0);
  return received - paid;
}

/**
 * The locked household result (BI-01, D2-11):
 *   result = revenue − investimento − costs + sublet_net
 * sublet_net is added EXACTLY ONCE; the gross legs are already excluded from revenue/costs.
 *
 * SQL mirror (0007 v_pnl_monthly.result).
 */
export function householdResult(b: PnlBuckets): number {
  return b.revenue - b.investimento - b.costs + b.subletNet;
}

/**
 * Household margin (BI-01, UI-SPEC "% of net revenue"):
 *   margin = result / revenue
 * Returns `null` when revenue is 0 — never divide by zero (mirrors `nullif(revenue,0)` SQL).
 *
 * SQL mirror (0007 v_pnl_monthly.margin = result / nullif(revenue,0)).
 */
export function householdMargin(b: PnlBuckets): number | null {
  if (b.revenue === 0) return null;
  return householdResult(b) / b.revenue;
}

/**
 * Operating margin (BI-08, D5-19 — the house-as-business reframe):
 *   operatingMargin = revenue − costs + sublet_net
 * investimento is DELIBERATELY NOT subtracted — investing is BELOW the line (the €4k legs feed the
 * €100k goal, they are not an operating cost). This is the new HEADLINE figure; `householdResult`
 * (which DOES subtract investimento) is shown below the line, and the old "EXCLUDED / −44,5%" label
 * is dropped. Same buckets as `householdResult`, minus the investimento term.
 */
export function operatingMargin(b: PnlBuckets): number {
  return b.revenue - b.costs + b.subletNet;
}

/**
 * Operating margin as a share of revenue (BI-08 companion): operatingMargin / revenue. Returns
 * `null` when revenue is 0 — never divide by zero (marts null-not-NaN convention).
 */
export function operatingMarginPct(b: PnlBuckets): number | null {
  if (b.revenue === 0) return null;
  return operatingMargin(b) / b.revenue;
}

/** Budget-vs-actual grain (BI-02, D2-14): cost-center grain when no category is pinned. */
export type BudgetGrain = "cost_center" | "category";

export interface BudgetVsActualInput {
  costCenter: string;
  categoryId: string | null;
  budget: number;
  actual: number;
}

export interface BudgetVsActualResult {
  costCenter: string;
  categoryId: string | null;
  grain: BudgetGrain;
  budget: number;
  actual: number;
  /** budget − actual; negative = over budget. */
  remaining: number;
}

/**
 * Budget-vs-actual at BOTH grains (BI-02, D2-14): a row with `categoryId === null` is a
 * cost-center-grain budget; a row with `categoryId` set is a category-grain budget. The
 * grain is derived from the presence of `categoryId` — the SQL join applies the matching
 * grain via `(b.category_id is null or t.category_id = b.category_id)`.
 *
 * NOTE (D2-12): this helper only computes budget−actual for budget rows that EXIST. Absent
 * budgets are NOT synthesized as €0 caps — the caller (and v_costcenter_bva) drives off the
 * `budgets` rows, so "not set" surfaces as the absence of a row, never a fake €0 cap.
 *
 * SQL mirror (0007 v_costcenter_bva).
 */
export function budgetVsActual(input: BudgetVsActualInput): BudgetVsActualResult {
  const grain: BudgetGrain = input.categoryId === null ? "cost_center" : "category";
  return {
    costCenter: input.costCenter,
    categoryId: input.categoryId,
    grain,
    budget: input.budget,
    actual: input.actual,
    remaining: input.budget - input.actual,
  };
}

/** The label used when a cost row carries no category (D2-01 graceful-degrade). */
export const UNCATEGORIZED_LABEL = "Uncategorized";

export interface BreakdownSlice {
  label: string;
  amount: number;
}

/**
 * Category breakdown with the graceful-degrade Uncategorized bucket (BI-03, D2-01): cost
 * rows are grouped by category label; a `categoryId === null` row lands under
 * "Uncategorized" rather than being dropped. `labelOf` resolves a categoryId to its name
 * (the SQL view does this via a join + `coalesce(category_name,'Uncategorized')`).
 *
 * SQL mirror (0007 v_category_breakdown). Rows are never dropped — the breakdown always
 * sums to total costs (the warning sign in Pattern 9 is a breakdown that sums to less).
 */
export function categoryBreakdown(
  rows: MartTx[],
  labelOf: (categoryId: string) => string,
): BreakdownSlice[] {
  const byLabel = new Map<string, number>();
  for (const r of rows.filter((x) => x.flowType === "cost")) {
    const label = r.categoryId === null ? UNCATEGORIZED_LABEL : labelOf(r.categoryId);
    byLabel.set(label, (byLabel.get(label) ?? 0) + r.amount);
  }
  return [...byLabel.entries()].map(([label, amount]) => ({ label, amount }));
}

/**
 * Category-as-%-of-revenue (BI-03, D2-15): each category's cost as a share of that period's
 * salary revenue. Returns `null` when revenue is 0 (no divide-by-zero — mirrors
 * `nullif(revenue,0)` in SQL).
 *
 * SQL mirror (0007 v_pct_of_revenue = category_cost / nullif(revenue,0)).
 */
export function pctOfRevenue(categoryCost: number, revenue: number): number | null {
  if (revenue === 0) return null;
  return categoryCost / revenue;
}

/**
 * Months-of-reserve (BI-07, UI-SPEC §Conventions): liquid cash ÷ trailing-3-month average
 * monthly costs. Guards divide-by-zero — returns `null` when there is no cost history or the
 * trailing average is 0 (a zero-cost burn rate yields infinite runway, surfaced as null/∞ in
 * the UI rather than a NaN).
 *
 * SQL mirror (the inputs v_balance_trend + v_pnl_monthly.costs expose; the division is done
 * in TS here because it spans the balance and P&L marts).
 */
export function monthsOfReserve(cash: number, trailingMonthlyCosts: number[]): number | null {
  if (trailingMonthlyCosts.length === 0) return null;
  const avg =
    trailingMonthlyCosts.reduce((acc, c) => acc + c, 0) / trailingMonthlyCosts.length;
  if (avg === 0) return null;
  return cash / avg;
}

// Plan-frontmatter export aliases (the canonical names the rest of Phase 2 imports). The
// pure helpers above are the implementation; these expose the formula under the names the
// plan + downstream plans reference, so `computePnl(buckets)` returns the full P&L row and
// `computeMonthsOfReserve` is the months-of-reserve helper.

/** The full computed P&L row for a period (the locked formula, BI-01). */
export interface ComputedPnl extends PnlBuckets {
  result: number;
  margin: number | null;
}

/**
 * computePnl — the canonical P&L row from the four buckets (BI-01, D2-11). Mirrors
 * v_pnl_monthly: result = revenue − investimento − costs + sublet_net; margin via nullif.
 */
export function computePnl(b: PnlBuckets): ComputedPnl {
  return {
    ...b,
    result: householdResult(b),
    margin: householdMargin(b),
  };
}

/** computeMonthsOfReserve — alias of monthsOfReserve under the plan-frontmatter name (BI-07). */
export const computeMonthsOfReserve = monthsOfReserve;

/**
 * Net worth at a point in time (BI-07): the sum of the latest balance per account. The SQL
 * view (v_balance_trend) does the "latest balance per account per day" pick in SQL; this
 * pure mirror takes the already-latest per-account balances and sums them.
 *
 * SQL mirror (0007 v_balance_trend.net_worth).
 */
export function netWorth(latestBalancePerAccount: number[]): number {
  return latestBalancePerAccount.reduce((acc, b) => acc + b, 0);
}

// ---------------------------------------------------------------------------
// Typed pgView(...).existing() handles — the RSC read surface.
//
// The DDL lives in drizzle/0007_marts.sql (hand-written, applied LIVE in the [BLOCKING]
// checkpoint). `.existing()` does NOT generate DDL; it only describes the column shape so
// Server Components get a typed `.select()` under the caller's JWT + RLS (security_invoker).
// Column types mirror the SQL: period_key int; money numeric(14,2); labels text.
// ---------------------------------------------------------------------------

const money = (name: string) => numeric(name, { precision: 14, scale: 2 });

/** v_pnl_monthly — per-period household P&L on the dim_calendar spine (BI-01/04). */
export const vPnlMonthly = pgView("v_pnl_monthly", {
  periodKey: integer("period_key").notNull(),
  revenue: money("revenue").notNull(),
  costs: money("costs").notNull(),
  investimento: money("investimento").notNull(),
  subletNet: money("sublet_net").notNull(),
  result: money("result").notNull(),
  margin: numeric("margin", { precision: 14, scale: 6 }),
}).existing();

/** v_sublet_pnl — the standalone Sublocação profit-center P&L (D2-06/07/08). */
export const vSubletPnl = pgView("v_sublet_pnl", {
  periodKey: integer("period_key").notNull(),
  subletRevenue: money("sublet_revenue").notNull(),
  subletCosts: money("sublet_costs").notNull(),
  subletNet: money("sublet_net").notNull(),
}).existing();

/** v_costcenter_bva — budget-vs-actual at cost-center AND category grain (BI-02/D2-14). */
export const vCostcenterBva = pgView("v_costcenter_bva", {
  costCenter: text("cost_center").notNull(),
  categoryId: text("category_id"),
  periodKey: integer("period_key").notNull(),
  budget: money("budget").notNull(),
  actual: money("actual").notNull(),
}).existing();

/** v_category_breakdown — cost breakdown by category/account/person, Uncategorized always present (BI-03/D2-01). */
export const vCategoryBreakdown = pgView("v_category_breakdown", {
  periodKey: integer("period_key").notNull(),
  grain: text("grain").notNull(),
  bucketKey: text("bucket_key"),
  bucketLabel: text("bucket_label").notNull(),
  costs: money("costs").notNull(),
}).existing();

/** v_pct_of_revenue — each category's cost as a share of salary revenue (BI-03/D2-15). */
export const vPctOfRevenue = pgView("v_pct_of_revenue", {
  periodKey: integer("period_key").notNull(),
  categoryId: text("category_id"),
  categoryLabel: text("category_label").notNull(),
  categoryCost: money("category_cost").notNull(),
  revenue: money("revenue").notNull(),
  pctOfRevenue: numeric("pct_of_revenue", { precision: 14, scale: 6 }),
}).existing();

/** v_balance_trend — net worth per day across the dim_calendar spine (BI-07). */
export const vBalanceTrend = pgView("v_balance_trend", {
  date: text("date").notNull(),
  periodKey: integer("period_key").notNull(),
  netWorth: money("net_worth").notNull(),
}).existing();

/** v_home_kpis — the 4 headline KPIs for the Home page, per period (BI-05). */
export const vHomeKpis = pgView("v_home_kpis", {
  periodKey: integer("period_key").notNull(),
  revenue: money("revenue").notNull(),
  investimento: money("investimento").notNull(),
  costs: money("costs").notNull(),
  subletNet: money("sublet_net").notNull(),
  result: money("result").notNull(),
  margin: numeric("margin", { precision: 14, scale: 6 }),
  netWorth: money("net_worth").notNull(),
}).existing();

// Keep `AnyPgColumn` referenced for downstream typed-column helpers without an unused import.
export type MartColumn = AnyPgColumn;
